site_name: Documentation
site_description: >-
  R-Type is a side-scrolling shoot-em-up arcade game produced by Irem in 1987. 
  The player controls a space fighter named the R-9 to defend humanity against a mysterious powerful alien lifeform known as the Bydo. 
  This repository contains the documentation for the game, including the source code, build instructions, and more.

# Repository
repo_name: AnalyticAce/r-type-docs
repo_url: https://github.com/AnalyticAce/r-type-docs
# Copyright
copyright: Copyright &copy; 2024 R-Type-Group - All rights reserved.

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  logo: assets/image/logo.png
  favicon: assets/image/favicon.ico
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
    property: G-8WHJ2N4SHC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
      - System Requirements: system_requirements.md
      - Installation:
          - Pre-requisites: installation/prerequisites.md
          - Build Instructions: installation/build_instructions.md
          - Running the Application: installation/running.md
  - Architecture:
      - Overview: architecture/overview.md
      - Diagrams: architecture/diagrams.md
      - ECS Design Pattern: architecture/ecs.md
  - Developer Guide:
      - Code Structure: developer_guide/code_structure.md
      - Key Classes & Modules: developer_guide/key_classes.md
      - API Documentation: developer_guide/api_documentation.md
      - How-To Guides: developer_guide/how_to_guides.md
      - Contributing: developer_guide/contributing.md
  - Networking:
      - Protocol Documentation: protocol.md
      - Security & Performance: security_performance.md
  - Testing & CI/CD:
      - Unit Tests: testing_ci_cd.md
      - Continuous Integration: ci_cd.md
  - User Guide:
      - Gameplay Overview: user_documentation/gameplay_overview.md
      - Controls: user_documentation/controls.md
      - Multiplayer Setup: user_documentation/multiplayer_setup.md
      - FAQ: user_documentation/faq.md
  - Additional Information:
      - Accessibility: accessibility.md
      - References: references.md
      - Glossary: appendix/glossary.md
      - Change Log: appendix/change_log.md
      - License Information: appendix/license.md
